name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      run: |
        IMAGE_NAME=chinjuvarghese/2048-app
        IMAGE_TAG=latest
        docker build -t $IMAGE_NAME:$IMAGE_TAG .
        docker push $IMAGE_NAME:$IMAGE_TAG

    - name: Setup kubectl
      uses: aws-actions/setup-kubectl@v1  
      with:
        version: 'latest'

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name game-2048-cluster --region us-east-1

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f game-2048-deployment.yaml
        kubectl apply -f game-2048-service.yaml
        kubectl apply -f ingress.yaml

